# Generated by Django 4.0.6 on 2022-07-31 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=255)),
                ('property_type', models.CharField(max_length=255)),
                ('property_location', models.CharField(max_length=255)),
                ('property_description', models.CharField(max_length=255)),
                ('property_owner', models.CharField(choices=[('Owner 1', 'Owner 1'), ('Owner 2', 'Owner 2'), ('Owner 3', 'Owner 3'), ('Owner 4', 'Owner 4')], max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('property_type', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('rent_rate', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('gender', models.CharField(choices=[('F', 'F'), ('M', 'M')], max_length=100, null=True)),
                ('owner', models.CharField(choices=[('Owner 1', 'Owner 1'), ('Owner 2', 'Owner 2'), ('Owner 3', 'Owner 3'), ('Owner 4', 'Owner 4')], max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
