# Generated by Django 4.0.6 on 2022-08-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_propertyinfo_delete_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(blank=True, max_length=255)),
                ('paid_to', models.CharField(blank=True, max_length=255)),
                ('payment_desc', models.CharField(blank=True, max_length=255)),
                ('payment_amount', models.FloatField()),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('tenant', models.CharField(blank=True, max_length=255)),
                ('payment_desc', models.CharField(blank=True, max_length=255)),
                ('payment_amount', models.FloatField()),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
