# Generated by Django 4.0.6 on 2022-09-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media/'),
        ),
        migrations.DeleteModel(
            name='Files',
        ),
    ]
