# Generated by Django 4.0.6 on 2022-09-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0006_rename_file_rent_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='files',
        ),
        migrations.AddField(
            model_name='rent',
            name='file',
            field=models.FileField(default=None, upload_to='media/'),
        ),
    ]
