# Generated by Django 4.0.6 on 2022-09-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0007_remove_rent_files_rent_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media/'),
        ),
    ]
