# Generated by Django 4.0.6 on 2022-09-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0009_alter_rent_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='file',
        ),
        migrations.AddField(
            model_name='rent',
            name='files',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media/'),
        ),
    ]
