# Generated by Django 4.0.6 on 2022-09-24 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0011_owner_alter_propertyinfo_property_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='firstname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='middlename',
        ),
    ]
